services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - STORAGE_PROVIDER=local
    volumes:
      - recipe_uploads:/app/uploads
      - ./src:/app/src
    depends_on:
      - db

volumes:
  pgdata:
  recipe_uploads:
